# -*- coding: utf-8 -*-
"""SQL Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mfcCVjk-vJMQ9jKa9qbzylPesW-ndJFu
"""

!pip install -q gradio transformers torch reportlab requests

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_name = "ibm-granite/granite-3.3-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto"
)

prompt = "Convert to SQL: Show users who signed up last month"
inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

outputs = model.generate(**inputs, max_new_tokens=100)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

SCHEMA = {
    "users": ["id", "name", "email", "signup_date", "age", "country", "status"],
    "orders": ["id", "user_id", "product_name", "amount", "order_date", "status"],
    "products": ["id", "name", "price", "category", "stock"],
    "transactions": ["id", "user_id", "amount", "date", "type"]
}

DANGEROUS_KEYWORDS = [
    "DROP", "DELETE", "ALTER", "TRUNCATE",
    "INSERT", "UPDATE", "EXEC", "EXECUTE"
]

import re

def is_safe(user_input):
    text = user_input.upper()

    # Block dangerous keywords
    for keyword in DANGEROUS_KEYWORDS:
        if keyword in text:
            return False

    # Block injection patterns
    patterns = [";", "--", "/*", "*/", "xp_", "sp_"]
    for pattern in patterns:
        if pattern in text:
            return False

    return True

def get_table_name(query):
    query = query.lower()

    if any(word in query for word in ["user", "users", "customer", "account"]):
        return "users"

    if any(word in query for word in ["order", "purchase", "buy"]):
        return "orders"

    if any(word in query for word in ["product", "item", "goods"]):
        return "products"

    if any(word in query for word in ["transaction", "payment", "transfer"]):
        return "transactions"

    return None

def extract_conditions(query):
    conditions = []

    # Amount detection
    match = re.search(r'greater than (\d+)', query.lower())
    if match:
        conditions.append(f"amount > {match.group(1)}")

    # Last week
    if "last week" in query.lower():
        conditions.append("DATE(date) >= DATE('now', '-7 days')")

    # Last month
    if "last month" in query.lower():
        conditions.append("DATE(signup_date) >= DATE('now', '-1 month')")

    return conditions

def generate_sql(user_input):
    if not is_safe(user_input):
        return "⚠️ Unsafe query detected!"

    table = get_table_name(user_input)

    if not table:
        return "⚠️ Could not detect table."

    conditions = extract_conditions(user_input)

    query = f"SELECT * FROM {table}"

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    query += " LIMIT 10"

    return query

import gradio as gr

history = []

def chat_function(user_input):
    sql_query = generate_sql(user_input)
    history.append((user_input, sql_query))
    return history

with gr.Blocks() as demo:
    gr.Markdown("# SQL Query Generator")

    chatbot = gr.Chatbot()
    msg = gr.Textbox(label="Enter your request")

    msg.submit(chat_function, msg, chatbot)

demo.launch(share=True)

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.platypus import Spacer
from datetime import datetime

def export_pdf():
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("SQL Query Report", styles['Title']))
    elements.append(Spacer(1, 12))

    for user, sql in history:
        elements.append(Paragraph(f"User: {user}", styles['Normal']))
        elements.append(Paragraph(f"SQL: {sql}", styles['Code']))
        elements.append(Spacer(1, 12))

    doc.build(elements)
    return filename

demo.launch(
    share=True,
    show_error=True,
    show_api=False
)